### ISSUE TITLE
jax v0.4.34 breaks e3nn_jax import

### ISSUE THREAD

**Issue by BoltMaxwell** [e3nn/e3nn-jax#83]
The error thrown: AttributeError: jax.core.pp_eqn_rules was removed in JAX v0.4.34. Which makes sense in the newest release: https://github.com/jax-ml/jax/releases. Which specifies the removal of the pretty printing tools

**Comment by mitkotak** [comment]
Seems to be coming from equinox but not sure which part specifically @ameya98 
```bash
Traceback (most recent call last):
  File "/home/mkotak/atomic_architects/projects/flashtensorproduct/benchmark.py", line 5, in <module>
    import e3nn_jax as e3nn
  File "/home/mkotak/atomic_architects/lib/e3nn-jax/e3nn_jax/__init__.py", line 122, in <module>
    from e3nn_jax import flax, haiku, equinox
  File "/home/mkotak/atomic_architects/lib/e3nn-jax/e3nn_jax/equinox.py", line 2, in <module>
    import equinox
  File "/home/mkotak/atomic_architects/lib/e3nn-jax/.venv/lib/python3.10/site-packages/equinox/__init__.py", line 3, in <module>
    from . import debug as debug, internal as internal, nn as nn
  File "/home/mkotak/atomic_architects/lib/e3nn-jax/.venv/lib/python3.10/site-packages/equinox/internal/__init__.py", line 46, in <module>
    from ._finalise_jaxpr import (
  File "/home/mkotak/atomic_architects/lib/e3nn-jax/.venv/lib/python3.10/site-packages/equinox/internal/_finalise_jaxpr.py", line 186, in <module>
    from ._noinline import noinline_p
  File "/home/mkotak/atomic_architects/lib/e3nn-jax/.venv/lib/python3.10/site-packages/equinox/internal/_noinline.py", line 379, in <module>
    jax.core.pp_eqn_rules[noinline_p] = _noinline_pretty_print
  File "/home/mkotak/atomic_architects/lib/e3nn-jax/.venv/lib/python3.10/site-packages/jax/_src/deprecations.py", line 52, in getattr
    raise AttributeError(message)
AttributeError: jax.core.pp_eqn_rules was removed in JAX v0.4.34.
```

**Comment by mitkotak** [comment]
Upgrading to the latest equinox version seems to have fixed this for [me](https://github.com/patrick-kidger/equinox/issues/869). Can you try this out ? @BoltMaxwell

**Comment by ameya98** [comment]
Closing since this seems like an equinox issue.
